### ISSUE TITLE
External Search

### ISSUE THREAD

**Issue by eelzi382** [dulibrarytech/primo-ui#1]
**Describe the solution you'd like**
Add an External Search facet section at that pulls the existing search in Primo into another system. The three facets/systems we would like to use are Worldcat.org, Prospector and Google Scholar.
Worldcat.org
http://encore.coalliance.org/iii/encore/?lang=eng&suite=def
https://scholar.google.com/schhp?hl=en&inst=10364086606605717788

**Is your feature request related to a problem? Please describe.**
If applicable, a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
We get constant requests for a feature that will pull the existing search into Prospector - we currently have it set up so a failed search can be pulled into Prospector, but our users ask for a non-failed search to do so as well. We also get many requests for a similar set-up for Worldcat.org. Google Scholar has not been requested, but since we are looking at the other two, and some institutions in the Orbis Cascade Alliance have set it up, it makes sense to do all three at once.

**Affected Systems**
If known, in what system the change needs to happen e.g. Alma, Primo.
Primo

**Additional Comments**
Put any screenshots or examples that highlight the current issue and/or desired enhancement here. Also indicate any alternatives you explored or other potential solutions.

Here is where you can find how a failed search links to prospector. Fernando wrote this code.
https://du-primo.hosted.exlibrisgroup.com/primo-explore/search?query=any,contains,kighsf&tab=default_tab&search_scope=everything_scope&vid=01UODE_MAIN&lang=en_US&offset=0

Here is Primo example of the external search facet. Perform any search and you will see the links to Worldcat and Google Scholar at the top of the facets. Note that they are linking to a different version of Worldcat, not worldcat.org.
https://www.lib.washington.edu/

And here is the Orbis cascade information on how they set up external search.
https://github.com/pdxlibrary/Primo-Send-Search-To

**Comment by kimpham54** [comment]
see code in js file that fernando worked on

**Comment by josephlabrecque** [comment]
Just popping this in here so we are sure not to lose it. Nearly there on this one. 

`        var search_prospector_label = "Search Prospector";
        var prospector_search_url = "https://encore.coalliance.org/iii/encore/search/C__S";
        var search_google_scholar_label = "Search Google Scholar";
        var google_scholar_search_url = "https://scholar.google.com/scholar?hl=en&as_sdt=0%2C6&inst=10364086606605717788&q=";
        var search_worldcat_label = "Search WorldCat";
        var worldcat_search_url = "https://www.worldcat.org/search?q=";
        var search_string = "";
        console.log('addOtherSearches');
        if(document.getElementById("searchBar").value.length > 0) 
            search_string = document.getElementById("searchBar").value;
        else if(document.getElementById("input_freeText0").value.length > 0 && document.getElementById("input_freeText1").value.length > 0 && document.getElementById("input_freeText2").value.length > 0) 
            search_string = document.getElementById("input_freeText0").value + " " + document.getElementById("input_freeText1").value + " " + document.getElementById("input_freeText2").value;
            var newsearchoptions = document.createElement('span');
            newsearchoptions.innerHTML = '<div id="OtherPlacesToSearchContainer"><h2 class="sidebar-title">Other Places to Search</h2><ol class="EXLFacetsList EXLFacetsListPreview"><li><a href="'+prospector_search_url+encodeURIComponent(search_string)+'__Orightresult__U?lang=eng&suite=def" title="Search Prospector">'+search_prospector_label+'</a></li><li><a href="'+google_scholar_search_url+encodeURIComponent(search_string)+'" title="Search Google Scholar">'+search_google_scholar_label+'</a></li><li><a href="'+worldcat_search_url+encodeURIComponent(search_string)+'" title="Search WorldCat">'+search_worldcat_label+'</a></li></ol></div>';
            document.getElementById("facets").getElementsByClassName("sidebar-section")[0].prepend(newsearchoptions);`

**Comment by josephlabrecque** [comment]
![image](https://user-images.githubusercontent.com/3355144/52236313-b7251b80-2883-11e9-81a6-f28aa5aeef50.png)

They actually work too... Sick ;)

**Comment by eelzi382** [comment]
These are great!! I want to do a little more testing and get approval from our Metadata and Discovery committee and then from Reference - they may want some labels changed. I'll let you know within a week or so. But so far these are awesome!

**Comment by eelzi382** [comment]
Hi Joseph, 

We have two issues before we can push live. First - can we have each of the three external tools open in a new tab? Second, in all browsers, we find that after the initial search is done in Compass, if a second search is done or facets selected, the external search options disappear until the page is refreshed. Can this be fixed? Thanks!

**Comment by josephlabrecque** [comment]
I can do the tab thing easy - the other one I just need to figure out a spot to refresh the search stuff i generate.

**Comment by josephlabrecque** [comment]
Right now, I am rendering the external bits on app load. I need it to render when a search process completes instead. How can I hook into that event within the system? Are there docs around event hooks for Primo?

**Comment by eelzi382** [comment]
Pardon my ignorance, but I don't know what that means. Hopefully Kim or Fernando can help answer that when they are back.

**Comment by kimpham54** [comment]
hey @josephlabrecque, looks like you can extend primo with angular directives. they don't have a lot of documentation, this is the best resource that i could find: https://github.com/ExLibrisGroup/primo-explore-package/tree/master/VIEW_CODE/js. we can talk through next week if you like

**Comment by josephlabrecque** [comment]
That may be what I'm looking for - will look more deeply on Monday.

**Comment by josephlabrecque** [comment]
Okay - should be good now!

**Comment by eelzi382** [comment]
Everything is working as expected! I'll push the changes live on March 18th. Thanks so much for working on this!
