### ISSUE TITLE
Hide Year & Volume from Request Options

### ISSUE THREAD

**Issue by eelzi382** [dulibrarytech/primo-ui#2]
**Describe the solution you'd like**
In a full record view that have multiple items (such as Journals, or a multi-volume set), 3 limiting options show: Year, Volume and Year/Volume. We want to hide the Year and Volume options, leaving only Year/Volume.

**Is your feature request related to a problem? Please describe.**
If applicable, a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
LCPP and Cataloging only use the Year/Volume field, so the Year and Volume drop downs are always empty. This is confusing to users.

**Affected Systems**
If known, in what system the change needs to happen e.g. Alma, Primo.
Alma

**Additional Comments**
Put any screenshots or examples that highlight the current issue and/or desired enhancement here. Also indicate any alternatives you explored or other potential solutions.
This record is a good example: https://du-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01UODE_ALMA21637400060002766&context=L&vid=01UODE_MAIN&search_scope=everything_scope&tab=default_tab&lang=en_US

**Comment by josephlabrecque** [comment]
Seems like the styles are not being applied to this content since the content itself is being pulled in via an iframe - looks like it is from Alma? 

![image](https://user-images.githubusercontent.com/3355144/52217274-5979da80-2855-11e9-8654-aeffad79ebd8.png)

**Comment by kimpham54** [comment]
@josephlabrecque mashup files live in alma - https://knowledge.exlibrisgroup.com/Alma/Knowledge_Articles/How_to_Configure_a_CSS_Skin_for_the_Alma_Services_Page_in_Primo%3F

**Comment by eelzi382** [comment]
![image](https://user-images.githubusercontent.com/45856330/52294640-1132e900-2937-11e9-8a98-67477b185660.png)

**Comment by josephlabrecque** [comment]
Okay... I uploaded a new "skin2" to Alma days ago with no effect. Went into Primo today to perform the remaining actions outlined in that link and can only think there must be something else we need to do as it isn't taking. 

(BTW - those instructions also seem outdated)

**Comment by josephlabrecque** [comment]
Scratch that - I can confirm the changes ARE being included... but they seem not the apply to the targeted elements for some reason. Will have to research more...

**Comment by josephlabrecque** [comment]
Okay. "skin2" is being included in the iframe content for "Access Online" just fine but NOT in "Find in Library" where we need it. That is the problem.

What is the difference?

**Comment by eelzi382** [comment]
Ahh, okay. Find in Library is pulling from physical items in Alma, and Access Online is pulling from either electronic it ems in Alma, or via the article linker. I went in and it looks like you already found in the mapping tables what needed to change. The last step after saving those setting is to deploy. I’ve done that and so it should apply to both get it (Find in Library) and view it (Access Online) now.

**Comment by josephlabrecque** [comment]
![image](https://user-images.githubusercontent.com/3355144/52505891-295e6e80-2baa-11e9-9da4-a36896aee39a.png)

Seems to have a different identifier in that iframe. The "Access Online" content reads "skin2" but not this one.

**Comment by eelzi382** [comment]
Yeah, I can see that now as well.. The GetIt section is pointing to the OTB mashup from this month’s release.

I’ll look more on Monday, but it does look like everything is correctly configured. They roll out a monthly release that often causes unexpected issues. Since the GetIt iframe is pointing at a release that came out this week, I have a feeling that might be it. In which case I have to open a ticket with ExL.

Thanks!
Erin

**Comment by josephlabrecque** [comment]
Think this is working now?
![image](https://user-images.githubusercontent.com/3355144/53369157-d1449d80-3907-11e9-8350-a6fbd530fa37.png)

**Comment by eelzi382** [comment]
We've tested it and it looks to be working great! And all stakeholders have approved. I'll close this ticket and push the changes live on March 18 (I don't like to make any changes the last 2 weeks of a quarter).
