### ISSUE TITLE
Hide Chevrons in Sign-in Lightbox

### ISSUE THREAD

**Issue by eelzi382** [dulibrarytech/primo-ui#3]
**Describe the solution you'd like**
Hide the two chevrons on the sign-in lightbox. 

**Is your feature request related to a problem? Please describe.**
If applicable, a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
These chevrons are not clickable, even though all other chevrons in Primo are. This has confused out users - we get reports that they cannot get to the sign-in box because they are trying to only click on the chevron.

**Affected Systems**
If known, in what system the change needs to happen e.g. Alma, Primo.
Primo

**Additional Comments**
Put any screenshots or examples that highlight the current issue and/or desired enhancement here. Also indicate any alternatives you explored or other potential solutions.
IT@DU did some work on our sign-in screens, and their solution hid ALL chevrons in Primo - some of which are valuable advance/back buttons. I had to remove the code they added to the css, which was:
 
 md-icon[md-svg-icon="primo-ui:chevron-right"] {
     display: none;
}

I believe the code needs to be nested somewhere else so it limits to hiding the chevrons only in that lightbox, not the entire interface.

**Comment by josephlabrecque** [comment]
@eelzi382 How do I access the Primo front-end where the chevron problem exists? Can you provide a link I can reference?

**Comment by eelzi382** [comment]
Looks great! I will push live on March 18 with the other changes. Thanks for working on it!
