### ISSUE TITLE
Branding for Article Linker Page

### ISSUE THREAD

**Issue by eelzi382** [dulibrarytech/primo-ui#4]
We have a single article linker page that is shared among all three institutions. Right now it is branded as Ex Libris, but we would like to have it branded for all thee libraries - DU, Law & Iliff.

Here is an example of the page: 

https://du-primo.hosted.exlibrisgroup.com/primo-explore/openurl?ID=doi:10.1186%2Fs12917-019-1775-2&genre=article&atitle=Efficacy%20of%20fluralaner%20spot-on%20solution%20for%20the%20treatment%20of%20Ctenocephalides%20felis%20and%20Otodectes%20cynotis%20mixed%20infestation%20in%20naturally%20infested%20cats.&title=BMC%20Veterinary%20Research&issn=17466148&isbn=&volume=15&issue=1&date=2019&aulast=Bosco,%20Antonio&spage=1&pages=1-6&sid=EBSCO:Academic%20Search%20Complete:134147331&vid=01UODE_SERVICES&institution=01UODE&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true&lang=en_US

Ideally, the color scheme would remain the same, but in the top bar, the ExLibris logo and link would be taken away and the logos from each of the three libraries would be added above that. Logos are attached. If the logos could link to each of the three library catalogs, that would be great, but if not, then just static images is fine. 

Links to use: 
University Libraries: https://du-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=01UODE_MAIN&lang=en_US&sortby=rank
Law Library: https://du-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=01UODE_LAW&lang=en_US&sortby=rank
Iliff: https://du-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=01UODE_ILIFF&sortby=rank&lang=en_US

Portland State is an example of where they added a customized bar above the standard Ex Libris top bar. https://search.library.pdx.edu/primo-explore/search?vid=PSU&lang=en_US

I believe this is customized using the Alma mashup file. I know Fernando and Kim looked into how 
we could customize this - they might be able to provide more info and what was tried and didn't work.

Let me know if you have any questions, or if this doesn't make sense at all - I'd be happy to chat/show you in person.

![library-logo](https://user-images.githubusercontent.com/45856330/53514009-f3fbc100-3a83-11e9-9c86-0cb95da9f3c1.png)
![sturmcollegeoflaw_signature](https://user-images.githubusercontent.com/45856330/53514010-f3fbc100-3a83-11e9-9e2c-b7265b740d9b.png)
![mainlogo](https://user-images.githubusercontent.com/45856330/53514011-f3fbc100-3a83-11e9-88ea-113898410f1a.png)

**Comment by josephlabrecque** [comment]
It definitely is the Alma skin where this can be modified. Are we limited to CSS with this skin or can we include a JavaScript file along with it? I'll give it a shot anyhow.

**Comment by josephlabrecque** [comment]
Yeah... looks like only CSS - so I attempted to add images and JS in there and it errors on upload saying invalid folder structure. That's pretty limited!

**Comment by josephlabrecque** [comment]
I wonder whether we can set this flag someplace in the Alma config? 
![image](https://user-images.githubusercontent.com/3355144/53815883-ca2d1900-3f1f-11e9-96d8-d09e7b9608f2.png)

**Comment by eelzi382** [comment]
I’ll keep looking around, but an initial look at the configuration and their documentation didn’t come up with anything. Would it make sense if it pointed to images loaded into Primo? Is that a possibility?

**Comment by josephlabrecque** [comment]
Yes - I think we'd have to point to images hosted elsewhere since we can't seem to load them in via the skin. Interactivity is also an issue since we cannot use JS to manipulate the nodes of the document view.

**Comment by eelzi382** [comment]
Hi,

I’ve been looking around the listservs to see of anyone talks about customizing this services page, but haven’t found anything. But I did find a good example of somewhere that has customized it:

https://flinders-primo.hosted.exlibrisgroup.com/primo-explore/openurl?ctx_ver=Z39.88-2004&rft.genre=article&ctx_enc=info:ofi%2Fenc:UTF-8&url_ver=Z39.88-2004&url_ctx_fmt=infofi%2Ffmt:kev:mtx:ctx,infofi%2Ffmt:kev:mtx:ctx&rfr_id=info:sid%2FEntrez:PubMed&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:article&isCitationLinker=Y&sfx.title_search=exact&rft.date=&rft_id=info:pmid%2F16398896&rft.atitle=&rft.jtitle=&rft.volume=&rft.issue=&rft.spage=&rft.epage=&rft.issn=&rft.doi=&rft.aulast=&rft.aufirst=&rft.auinit=&rft.publisher=&rft.pubdate=&vid=FUL&institution=61FUL&url_ctx_val=&isSerivcesPage=true&lang=en_US

Maybe that will help?

**Comment by josephlabrecque** [comment]
Ah - great. This may help, yes.

**Comment by josephlabrecque** [comment]
Fram looking at their stuff- seems to be coming from Primo itself and not Alma. Will continue investigating. 

![image](https://user-images.githubusercontent.com/3355144/53887047-a977c880-3fde-11e9-9e83-f146c618e8d4.png)

Their comments indicate there is something in the JS that assists as well.

**Comment by josephlabrecque** [comment]
Okay - so the other university has their Primo stuff getting loaded up in this view - but in ours... only the Alma stuff ever gets loaded. ¯\_(ツ)_/¯

**Comment by eelzi382** [comment]
Hmmm. Okay – I’ll see if I can find any more info on that. I might have to ask the vendor.

**Comment by eelzi382** [comment]
Hi! I talked to ExL, and this is done in Primo. To get to the files go to the customization manager as you have for the other files, but in the top drop down, instead of choosing 01UODE_MAIN, use 01UODE_SERVICES. Then you can download and make adjustments to that package of files.

**Comment by josephlabrecque** [comment]
Ah - yep! I was able to trigger some JS from there. Awesome!

**Comment by josephlabrecque** [comment]
Let me know if there are any other adjustments that need to be made: 
![image](https://user-images.githubusercontent.com/3355144/54630184-de543880-4a3e-11e9-9ca9-648bfdf44bc9.png)

**Comment by eelzi382** [comment]
I’m going to make some color changes to the Main and Law logos and will send those back to you within the next few days. I think we might also want to makes the Iliff logo a little smaller, but I first want to see how the different colors on the other two look.

Thanks!

**Comment by josephlabrecque** [comment]
Yep - these are basically all three logos just filling up the space. I can make them as small as we need and change colors and all sorts of stuff.

**Comment by eelzi382** [comment]
I've attached new versions of the Main and Law logos - can we see how those look in the banner?
Thanks!

![MainLogo white](https://user-images.githubusercontent.com/45856330/54714226-11b5c680-4b16-11e9-8424-6d116ecb8340.png)
![SturmCollegeofLaw_Signature white](https://user-images.githubusercontent.com/45856330/54714240-17aba780-4b16-11e9-993a-f1064db7175f.png)

**Comment by josephlabrecque** [comment]
Looking better? 

![image](https://user-images.githubusercontent.com/3355144/54753595-0b235f80-4ba7-11e9-8093-6735dd39cff0.png)

**Comment by eelzi382** [comment]
Absolutely! This is great - I’ve conferred with our E-resources Manager and she agrees!
